# Generated by Django 3.2.9 on 2021-12-03 00:40

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20, null=True, validators=[user.models._PhoneValidator()], verbose_name='Номер телефона'),
        ),
    ]
